/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthenticatedPropertyManagementRouteImport } from './routes/_authenticated/property-management'
import { Route as AuthenticatedPersonalInvoiceRouteImport } from './routes/_authenticated/personal-invoice'
import { Route as AuthenticatedPayBillsRouteImport } from './routes/_authenticated/pay-bills'
import { Route as AuthenticatedContractorManagementRouteImport } from './routes/_authenticated/contractor-management'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'

const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPropertyManagementRoute =
  AuthenticatedPropertyManagementRouteImport.update({
    id: '/property-management',
    path: '/property-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPersonalInvoiceRoute =
  AuthenticatedPersonalInvoiceRouteImport.update({
    id: '/personal-invoice',
    path: '/personal-invoice',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedPayBillsRoute = AuthenticatedPayBillsRouteImport.update({
  id: '/pay-bills',
  path: '/pay-bills',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedContractorManagementRoute =
  AuthenticatedContractorManagementRouteImport.update({
    id: '/contractor-management',
    path: '/contractor-management',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contractor-management': typeof AuthenticatedContractorManagementRoute
  '/pay-bills': typeof AuthenticatedPayBillsRoute
  '/personal-invoice': typeof AuthenticatedPersonalInvoiceRoute
  '/property-management': typeof AuthenticatedPropertyManagementRoute
}
export interface FileRoutesByTo {
  '/auth': typeof AuthRoute
  '/admin': typeof AuthenticatedAdminRoute
  '/contractor-management': typeof AuthenticatedContractorManagementRoute
  '/pay-bills': typeof AuthenticatedPayBillsRoute
  '/personal-invoice': typeof AuthenticatedPersonalInvoiceRoute
  '/property-management': typeof AuthenticatedPropertyManagementRoute
  '/': typeof AuthenticatedIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRoute
  '/_authenticated/contractor-management': typeof AuthenticatedContractorManagementRoute
  '/_authenticated/pay-bills': typeof AuthenticatedPayBillsRoute
  '/_authenticated/personal-invoice': typeof AuthenticatedPersonalInvoiceRoute
  '/_authenticated/property-management': typeof AuthenticatedPropertyManagementRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/admin'
    | '/contractor-management'
    | '/pay-bills'
    | '/personal-invoice'
    | '/property-management'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/auth'
    | '/admin'
    | '/contractor-management'
    | '/pay-bills'
    | '/personal-invoice'
    | '/property-management'
    | '/'
  id:
    | '__root__'
    | '/_authenticated'
    | '/auth'
    | '/_authenticated/admin'
    | '/_authenticated/contractor-management'
    | '/_authenticated/pay-bills'
    | '/_authenticated/personal-invoice'
    | '/_authenticated/property-management'
    | '/_authenticated/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/property-management': {
      id: '/_authenticated/property-management'
      path: '/property-management'
      fullPath: '/property-management'
      preLoaderRoute: typeof AuthenticatedPropertyManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/personal-invoice': {
      id: '/_authenticated/personal-invoice'
      path: '/personal-invoice'
      fullPath: '/personal-invoice'
      preLoaderRoute: typeof AuthenticatedPersonalInvoiceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pay-bills': {
      id: '/_authenticated/pay-bills'
      path: '/pay-bills'
      fullPath: '/pay-bills'
      preLoaderRoute: typeof AuthenticatedPayBillsRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/contractor-management': {
      id: '/_authenticated/contractor-management'
      path: '/contractor-management'
      fullPath: '/contractor-management'
      preLoaderRoute: typeof AuthenticatedContractorManagementRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRoute
  AuthenticatedContractorManagementRoute: typeof AuthenticatedContractorManagementRoute
  AuthenticatedPayBillsRoute: typeof AuthenticatedPayBillsRoute
  AuthenticatedPersonalInvoiceRoute: typeof AuthenticatedPersonalInvoiceRoute
  AuthenticatedPropertyManagementRoute: typeof AuthenticatedPropertyManagementRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRoute,
  AuthenticatedContractorManagementRoute:
    AuthenticatedContractorManagementRoute,
  AuthenticatedPayBillsRoute: AuthenticatedPayBillsRoute,
  AuthenticatedPersonalInvoiceRoute: AuthenticatedPersonalInvoiceRoute,
  AuthenticatedPropertyManagementRoute: AuthenticatedPropertyManagementRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
